spring:
  datasource:
    url: jdbc:postgresql://paku-aws-training-db2.ckpru3dte42n.ap-northeast-1.rds.amazonaws.com:5432/aws_training_db
    # url: jdbc:postgresql://localhost:5432/aws_training_db
    username: postgres
    password: trainingpw!2$iloveit
  sql:
    init:
      mode: always
